language:
  - node_js

node_js:
  - 9.5

cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules

before_install:
  - npm install -g lerna yarn babel-cli

install:
  - yarn bootstrap

stages:
  - name: branch-commit-build
    if: type IN (push) AND NOT branch = master

  - name: test-coverage-build
    if: type IN (cron)

  - name: pull-request-build
    if: type IN (pull_request)

  - name: master-commit-build
    if: type IN (push) AND branch = master

jobs:
  include:
    - stage: branch-commit-build
      script:
        - yarn lint && yarn ci:test

    - stage: test-coverage-build
      script:
        - yarn ci:coverage && ./node_modules/.bin/istanbul-coveralls

    - stage: pull-request-build
      script:
        - yarn lint && yarn ci:test && yarn ci:build:prod

    - stage: master-commit-build
      script:
        - yarn lint && yarn ci:test && yarn ci:build:prod
